Fixed missing GetBezControl1 and GetBezControl2 attributes
Fix error:  "An error occurred: 'PCB_SHAPE' object has no attribute 'GetBezControl1'" in KiCAD 6.0.2 and maintain backward compatibility.